---
- name: Update VMs
  hosts: all
  gather_facts: yes

  tasks:
    - name: Run update users role
      import_role:
        name: update_users

    - name: Configure Logical Volumes 
      import_role:
        name: configure_LVs
