---
- name: Show VM details
  hosts: all
  gather_facts: yes

  tasks:
    - name: Collecting processor type for host {{ inventory_hostname }}
      set_fact:
        proc_type: "{{item}}"
      with_items: "{{ansible_processor}}"

    - name: Collecting server type for host {{ inventory_hostname }}
      set_fact:
        server_type: "{{item}}"
      with_items: "{{ansible_product_name}}"

    - name: Collecting hosting server serial number for host {{ inventory_hostname }}
      set_fact:
        server_serial: "{{item}}"
      with_items: "{{ansible_product_serial}}"
    
    - name: Collecting default IP information for host {{ inventory_hostname }}
      set_fact:
        default_ip: "{{item}}"
      with_items: "{{ansible_default_ipv4.address}}"  

    - name: Show VM host information from facts gathered in this playbook
      debug:
        msg: "VM {{ inventory_hostname }} is running on server serial no:{{ server_serial }}, type:{{ server_type }}, processor:{{ proc_type}}"
        
    - name: Show VM default IP
      debug:
        var: default_ip
