---
- name: Ensure user condition is as expected
  ibm.power_aix.user:
    state: "{{ item.user_state }}"
    name: "{{ item.user_name }}"
    attributes:
      id: "{{ item.user_id}}"
  loop: "{{ users }}"
  when: ansible_distribution == "AIX"
