---
# Role to configure file systems defined in the vars/main.yml file
- name: Ensure logical volumes are configured as expected
  ibm.power_aix.filesystem:
    filesystem: "{{ item.fs_name }}"
    vg: "{{ item.vg_name }}"
    fs_type: "{{ item.fs_type }}"
    attributes: "size={{ item.fs_size}}"
    state: "{{ item.fs_state }}"
  loop: "{{ FSs }}"
  when: ansible_distribution == "AIX"

- name: Ensure logical volumes are configured as expected
  ibm.power_aix.mount:
    mount_all: all
